"""Add feedback column to performance_report

Revision ID: 8286931c815e
Revises: cd4e2f71e0b4
Create Date: 2024-12-15 08:30:17.069698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8286931c815e'
down_revision = 'cd4e2f71e0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_report', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
