"""Add is_active column to User model

Revision ID: cd4e2f71e0b4
Revises: 9f6581e54f4e
Create Date: 2024-12-13 20:05:44.578750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4e2f71e0b4'
down_revision = '9f6581e54f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('job_role',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('performance_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accuracy_level', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('confidence_level', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cv_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('performance_report_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cv', ['cv_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('report')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('performance_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('performance_report_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('cv_id')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('total_questions')
        batch_op.drop_column('confidence_level')
        batch_op.drop_column('accuracy_level')

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.alter_column('job_role',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
