"""Added job_description to CV

Revision ID: 8ca269b19a67
Revises: 6a1c762f8b04
Create Date: 2025-12-20 15:52:49.245677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca269b19a67'
down_revision = '6a1c762f8b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###
