"""Added feedback and status to InterviewSession

Revision ID: dc28bc07701f
Revises: 8ca269b19a67
Create Date: 2025-12-20 16:58:37.135909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc28bc07701f'
down_revision = '8ca269b19a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_session', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('status')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
